# This container is specific to the application.
# It contains configuration and data for other containers.
data:
   image: busybox
   container_name: AdminRendererBundle_data
   volumes:
       - ..:/srv
       - .home-developer:/home/developer
       - $SSH_AUTH_SOCK:/tmp/agent.sock

console:
   image: meuhmeuhconcept/php-console
   container_name: AdminRendererBundle_console
   volumes_from:
       - data
   env_file:
       - ./docker-compose.env
   environment:
       - DNSDOCK_IMAGE=console
       - SSH_AUTH_SOCK=/tmp/agent.sock